// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrtatbgpbtcfsmjtukjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlydGF0YmdwYnRjZnNtanR1a2pzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NDExNDQsImV4cCI6MjA2MDAxNzE0NH0.2LSg0v-SpRIYqJqd7npMSdl54dkUEPb1sgr-R8UMvcY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);